changeLogFile=changelog/changelog-master.yaml
url=jdbc:postgresql://db:5432/db_liquibase
username=postgres
password=12345
driver=org.postgresql.Driver
logLevel=INFO
searchPath=/liquibase/changelog,/liquibase/changelog/changelog

###  docker exec -it postgres_db psql -U postgres -d db_liquibase