services:
  postgres:
    image: postgres:15
    container_name: postgres_liquibase_new
    restart: always
    environment:
      POSTGRES_DB: liquibase_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"   
    volumes:
      - pg_data_new:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase_runner_new
    depends_on:
      - postgres
    volumes:
      - ./liquibase:/workspace
    working_dir: /workspace
    command: tail -f /dev/null

volumes:
  pg_data_new: