changeLogFile=changelog/db.changelog.xml

url=jdbc:postgresql://postgres:5432/liquibase_db
username=postgres
password=postgres

driver=org.postgresql.Driver
classpath=drivers/postgresql-42.7.10.jar

### docker run --rm -it -v %cd%/liquibase:/workspace --network host liquibase/liquibase --defaultsFile=/workspace/liquibase.properties update